export const ScreenPermission = [
  {
    translate: 'menu.home.title',
    hashName: 'home',
    menu: false,
    isView: false,
    isDetail: false,
    isCreated: false,
    isUpdated: false,
    isDeleted: false,
    isPrint: false,
    isImport: false,
    isExport: false,
  },
  {
    translate: 'menu.orders.title',
    hashName: 'orders',
    menu: false,
    isView: false,
    isDetail: false,
    isCreated: false,
    isUpdated: false,
    isDeleted: false,
    isPrint: false,
    isImport: false,
    isExport: false,
  },
  {
    translate: 'menu.service.serviceType',
    hashName: 'serviceType',
    menu: false,
    isView: false,
    isDetail: false,
    isCreated: false,
    isUpdated: false,
    isDeleted: false,
    isPrint: false,
    isImport: false,
    isExport: false,
  },
  {
    translate: 'menu.categories.title',
    hashName: 'categories',
    menu: false,
    isView: false,
    isDetail: false,
    isCreated: false,
    isUpdated: false,
    isDeleted: false,
    isPrint: false,
    isImport: false,
    isExport: false,
  },
  {
    translate: 'menu.categoryItems.title',
    hashName: 'categoryItems',
    menu: false,
    isView: false,
    isDetail: false,
    isCreated: false,
    isUpdated: false,
    isDeleted: false,
    isPrint: false,
    isImport: false,
    isExport: false,
  },
  {
    translate: 'menu.centers.title',
    hashName: 'centers',
    menu: false,
    isView: false,
    isDetail: false,
    isCreated: false,
    isUpdated: false,
    isDeleted: false,
    isPrint: false,
    isImport: false,
    isExport: false,
  },
  {
    translate: 'menu.setting.users',
    hashName: 'users',
    menu: false,
    isView: false,
    isDetail: false,
    isCreated: false,
    isUpdated: false,
    isDeleted: false,
    isPrint: false,
    isImport: false,
    isExport: false,
  },
];
